### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by mlin26** [slimgroup/WAVEFORM.jl#1]
Hi,

I'm using Julia 1.5.0. But the installation method seems doesn't work. It might require `Project.toml` file instead of `REQUIRE` file for the latest Julia.

```
Pkg.clone("git@github.com:slimgroup/JOLI.jl.git")
Pkg.clone("git@github.com:slimgroup/WAVEFORM.jl.git")
```

Could you tell me if there is a convenient way to install the code in the latest Julia? Or Do I need to use Julia 0.6 to install the code? Thanks!

**Comment by henryk-modzelewski** [comment]
Hi,

Unfortunately we never ported this package to newer versions of Julia, so it is 0.6. We talked about one of the students committing time to port it to newer Julia version, but I cannot give you the time frame. It is not going to be very near future for sure.

Sorry for inconvenience,
Cheers
